name: MikuMC CI - ZetaUtils

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    env:
      MAVEN_REPO_USER: ${{ secrets.MAVEN_REPO_USER }}
      MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWD }}
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build
        run: gradle shadowJar
      - name: Publish to repo
        run: gradlew publish
      - name: Upload Artifact
        uses: "actions/upload-artifact@v4"
        with:
          name: "${{ env.project_id_b }} CI Artifacts"
          path: "build/libs/*.jar"
